version: "3.8"
services:
  mongo: 
    image: docker.io/mongodb/mongodb-community-server:latest
    ports:
      - "3131:27017"
    container_name: mongocontainer 
  
  api:
    build: .
    ports:
      - "2140:6060"
    container_name: apicontainer
